import { Command } from 'commander';
import chalk from 'chalk';
import inquirer from 'inquirer';
import path from 'path';
import fs from 'fs-extra';
import { AuthService } from '../services/auth.js';
import { ProjectStructureService } from '../services/project-structure.js';

export const initCommand = new Command()
  .name('init')
  .description('Initialize a new Bizmanage project structure')
  .argument('[project-name]', 'Project name (optional)')
  .option('-a, --alias <alias>', 'Configuration alias to use (default: default)', 'default')
  .option('--force', 'Overwrite existing project')
  .action(async (projectName: string | undefined, options: { alias: string; force?: boolean }) => {
    console.log(chalk.blue('🚀 Initializing new Bizmanage project'));
    console.log();

    try {
      const authService = new AuthService();
      const config = await authService.getConfig(options.alias);

      if (!config) {
        console.log(chalk.red(`❌ No configuration found for alias "${options.alias}"`));
        console.log(chalk.dim('Run "bizmanage login" first to authenticate.'));
        process.exit(1);
      }

      // Get project name if not provided
      let finalProjectName = projectName;
      if (!finalProjectName) {
        const { name } = await inquirer.prompt([
          {
            type: 'input',
            name: 'name',
            message: 'Project name:',
            default: 'my-bizmanage-project',
            validate: (input: string) => {
              if (!input.trim()) {
                return 'Project name is required';
              }
              if (!/^[a-z0-9-_]+$/i.test(input)) {
                return 'Project name can only contain letters, numbers, hyphens, and underscores';
              }
              return true;
            }
          }
        ]);
        finalProjectName = name;
      }

      // Get additional project details
      const { description, createDirectory } = await inquirer.prompt([
        {
          type: 'input',
          name: 'description',
          message: 'Project description (optional):',
          default: `Bizmanage customizations for ${config.instanceUrl}`
        },
        {
          type: 'confirm',
          name: 'createDirectory',
          message: `Create new directory '${finalProjectName}'?`,
          default: true
        }
      ]);

      const projectPath = createDirectory 
        ? path.resolve(finalProjectName!)
        : path.resolve('.');

      // Check if project already exists
      if (await fs.pathExists(projectPath) && await fs.readdir(projectPath).then(files => files.length > 0)) {
        if (!options.force) {
          const { overwrite } = await inquirer.prompt([
            {
              type: 'confirm',
              name: 'overwrite',
              message: `Directory '${projectPath}' is not empty. Continue anyway?`,
              default: false
            }
          ]);

          if (!overwrite) {
            console.log(chalk.yellow('❌ Project initialization cancelled.'));
            process.exit(0);
          }
        }
      }

      console.log();
      console.log(chalk.dim(`Project path: ${projectPath}`));
      console.log(chalk.dim(`Instance: ${config.instanceUrl}`));
      console.log(chalk.dim(`Alias: ${options.alias}`));
      console.log();

      // Initialize project structure
      const projectService = new ProjectStructureService();
      
      await projectService.initializeProject(projectPath, {
        name: finalProjectName!,
        description,
        instanceUrl: config.instanceUrl,
        alias: options.alias
      });

      // Create .gitignore file for the project
      const gitignoreContent = `# Bizmanage Project - Generated Content
# These files are generated by 'bizmanage pull' and should not be committed

# Pulled data from Bizmanage platform (instance-specific)
src/objects/
src/backend/
src/reports/  
src/pages/
bizmanage.config.json

# Keep directory structure
!src/objects/.gitkeep
!src/backend/.gitkeep
!src/reports/.gitkeep  
!src/pages/.gitkeep

# Node.js
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# IDE files
.vscode/
.idea/
*.swp
*.swo

# OS files  
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# Environment variables
.env
.env.local
.env.*.local

# Temporary files
tmp/
temp/
*.tmp

# Backup files
*.bak
*.backup
`;

      await fs.writeFile(path.join(projectPath, '.gitignore'), gitignoreContent, 'utf8');

      console.log(chalk.green('🎉 Project initialized successfully!'));
      console.log();
      console.log(chalk.bold('Next steps:'));
      
      if (createDirectory) {
        console.log(chalk.dim(`  1. cd ${finalProjectName}`));
      }
      console.log(chalk.dim('  2. bizmanage pull --init'));
      console.log(chalk.dim('  3. Start customizing your code'));
      console.log(chalk.dim('  4. bizmanage push'));
      console.log();
      
      console.log(chalk.bold('Project structure:'));
      console.log(chalk.dim('  bizmanage.config.json  # Project configuration'));
      console.log(chalk.dim('  src/'));
      console.log(chalk.dim('    objects/             # Tables/views and their actions'));
      console.log(chalk.dim('    backend/             # Server-side scripts'));
      console.log(chalk.dim('    reports/             # SQL reports'));
      console.log(chalk.dim('    pages/               # Custom HTML pages'));

    } catch (error) {
      console.log();
      console.log(chalk.red(`❌ Initialization failed: ${error instanceof Error ? error.message : 'Unknown error'}`));
      process.exit(1);
    }
  });
